version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todolist
      DB_PORT: 5432
      JWT_SECRET: supersecret
    ports:
      - '5000:5000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  pgdata: 